### ISSUE TITLE
Use dedicated service account

### ISSUE THREAD

**Issue by jflowers** [RedHatGov/gitea-operator#18]
Create a dedicated ServiceAccount for the operator, in lieu of using system:default
this should be created from config/rbac/serviceaccount.yml

**Comment by roller1187** [comment]
Fixed by https://github.com/RedHatGov/devsecops-operator/pull/27

**Comment by roller1187** [comment]
We'll need to migrate the fixes to this repo once the code is ready to be moved wholesale.
